export const COUNTRIES = [
  {name:"Afghanistan",currency:"؋",code:"AFN",flag:"🇦🇫"},
  {name:"Albania",currency:"L",code:"ALL",flag:"🇦🇱"},
  {name:"Algeria",currency:"د.ج",code:"DZD",flag:"🇩🇿"},
  {name:"Andorra",currency:"€",code:"EUR",flag:"🇦🇩"},
  {name:"Angola",currency:"Kz",code:"AOA",flag:"🇦🇴"},
  {name:"Antigua and Barbuda",currency:"$",code:"XCD",flag:"🇦🇬"},
  {name:"Argentina",currency:"$",code:"ARS",flag:"🇦🇷"},
  {name:"Armenia",currency:"֏",code:"AMD",flag:"🇦🇲"},
  {name:"Australia",currency:"A$",code:"AUD",flag:"🇦🇺"},
  {name:"Austria",currency:"€",code:"EUR",flag:"🇦🇹"},
  {name:"Azerbaijan",currency:"₼",code:"AZN",flag:"🇦🇿"},
  {name:"Bahamas",currency:"$",code:"BSD",flag:"🇧🇸"},
  {name:"Bahrain",currency:"BD",code:"BHD",flag:"🇧🇭"},
  {name:"Bangladesh",currency:"৳",code:"BDT",flag:"🇧🇩"},
  {name:"Barbados",currency:"$",code:"BBD",flag:"🇧🇧"},
  {name:"Belarus",currency:"Br",code:"BYN",flag:"🇧🇾"},
  {name:"Belgium",currency:"€",code:"EUR",flag:"🇧🇪"},
  {name:"Belize",currency:"$",code:"BZD",flag:"🇧🇿"},
  {name:"Benin",currency:"Fr",code:"XOF",flag:"🇧🇯"},
  {name:"Bhutan",currency:"Nu",code:"BTN",flag:"🇧🇹"},
  {name:"Bolivia",currency:"Bs",code:"BOB",flag:"🇧🇴"},
  {name:"Bosnia and Herzegovina",currency:"KM",code:"BAM",flag:"🇧🇦"},
  {name:"Botswana",currency:"P",code:"BWP",flag:"🇧🇼"},
  {name:"Brazil",currency:"R$",code:"BRL",flag:"🇧🇷"},
  {name:"Brunei",currency:"$",code:"BND",flag:"🇧🇳"},
  {name:"Bulgaria",currency:"лв",code:"BGN",flag:"🇧🇬"},
  {name:"Burkina Faso",currency:"Fr",code:"XOF",flag:"🇧🇫"},
  {name:"Burundi",currency:"Fr",code:"BIF",flag:"🇧🇮"},
  {name:"Cambodia",currency:"៛",code:"KHR",flag:"🇰🇭"},
  {name:"Cameroon",currency:"Fr",code:"XAF",flag:"🇨🇲"},
  {name:"Canada",currency:"C$",code:"CAD",flag:"🇨🇦"},
  {name:"Cape Verde",currency:"$",code:"CVE",flag:"🇨🇻"},
  {name:"Central African Republic",currency:"Fr",code:"XAF",flag:"🇨🇫"},
  {name:"Chad",currency:"Fr",code:"XAF",flag:"🇹🇩"},
  {name:"Chile",currency:"$",code:"CLP",flag:"🇨🇱"},
  {name:"China",currency:"¥",code:"CNY",flag:"🇨🇳"},
  {name:"Colombia",currency:"$",code:"COP",flag:"🇨🇴"},
  {name:"Comoros",currency:"Fr",code:"KMF",flag:"🇰🇲"},
  {name:"Congo (DR)",currency:"Fr",code:"CDF",flag:"🇨🇩"},
  {name:"Congo (Republic)",currency:"Fr",code:"XAF",flag:"🇨🇬"},
  {name:"Costa Rica",currency:"₡",code:"CRC",flag:"🇨🇷"},
  {name:"Croatia",currency:"€",code:"EUR",flag:"🇭🇷"},
  {name:"Cuba",currency:"$",code:"CUP",flag:"🇨🇺"},
  {name:"Cyprus",currency:"€",code:"EUR",flag:"🇨🇾"},
  {name:"Czech Republic",currency:"Kč",code:"CZK",flag:"🇨🇿"},
  {name:"Denmark",currency:"kr",code:"DKK",flag:"🇩🇰"},
  {name:"Djibouti",currency:"Fr",code:"DJF",flag:"🇩🇯"},
  {name:"Dominica",currency:"$",code:"XCD",flag:"🇩🇲"},
  {name:"Dominican Republic",currency:"$",code:"DOP",flag:"🇩🇴"},
  {name:"Ecuador",currency:"$",code:"USD",flag:"🇪🇨"},
  {name:"Egypt",currency:"£",code:"EGP",flag:"🇪🇬"},
  {name:"El Salvador",currency:"$",code:"USD",flag:"🇸🇻"},
  {name:"Equatorial Guinea",currency:"Fr",code:"XAF",flag:"🇬🇶"},
  {name:"Eritrea",currency:"Nfk",code:"ERN",flag:"🇪🇷"},
  {name:"Estonia",currency:"€",code:"EUR",flag:"🇪🇪"},
  {name:"Eswatini",currency:"L",code:"SZL",flag:"🇸🇿"},
  {name:"Ethiopia",currency:"Br",code:"ETB",flag:"🇪🇹"},
  {name:"Fiji",currency:"$",code:"FJD",flag:"🇫🇯"},
  {name:"Finland",currency:"€",code:"EUR",flag:"🇫🇮"},
  {name:"France",currency:"€",code:"EUR",flag:"🇫🇷"},
  {name:"Gabon",currency:"Fr",code:"XAF",flag:"🇬🇦"},
  {name:"Gambia",currency:"D",code:"GMD",flag:"🇬🇲"},
  {name:"Georgia",currency:"₾",code:"GEL",flag:"🇬🇪"},
  {name:"Germany",currency:"€",code:"EUR",flag:"🇩🇪"},
  {name:"Ghana",currency:"₵",code:"GHS",flag:"🇬🇭"},
  {name:"Greece",currency:"€",code:"EUR",flag:"🇬🇷"},
  {name:"Grenada",currency:"$",code:"XCD",flag:"🇬🇩"},
  {name:"Guatemala",currency:"Q",code:"GTQ",flag:"🇬🇹"},
  {name:"Guinea",currency:"Fr",code:"GNF",flag:"🇬🇳"},
  {name:"Guinea-Bissau",currency:"Fr",code:"XOF",flag:"🇬🇼"},
  {name:"Guyana",currency:"$",code:"GYD",flag:"🇬🇾"},
  {name:"Haiti",currency:"G",code:"HTG",flag:"🇭🇹"},
  {name:"Honduras",currency:"L",code:"HNL",flag:"🇭🇳"},
  {name:"Hungary",currency:"Ft",code:"HUF",flag:"🇭🇺"},
  {name:"Iceland",currency:"kr",code:"ISK",flag:"🇮🇸"},
  {name:"India",currency:"₹",code:"INR",flag:"🇮🇳"},
  {name:"Indonesia",currency:"Rp",code:"IDR",flag:"🇮🇩"},
  {name:"Iran",currency:"﷼",code:"IRR",flag:"🇮🇷"},
  {name:"Iraq",currency:"ع.د",code:"IQD",flag:"🇮🇶"},
  {name:"Ireland",currency:"€",code:"EUR",flag:"🇮🇪"},
  {name:"Israel",currency:"₪",code:"ILS",flag:"🇮🇱"},
  {name:"Italy",currency:"€",code:"EUR",flag:"🇮🇹"},
  {name:"Ivory Coast",currency:"Fr",code:"XOF",flag:"🇨🇮"},
  {name:"Jamaica",currency:"$",code:"JMD",flag:"🇯🇲"},
  {name:"Japan",currency:"¥",code:"JPY",flag:"🇯🇵"},
  {name:"Jordan",currency:"JD",code:"JOD",flag:"🇯🇴"},
  {name:"Kazakhstan",currency:"₸",code:"KZT",flag:"🇰🇿"},
  {name:"Kenya",currency:"KSh",code:"KES",flag:"🇰🇪"},
  {name:"Kiribati",currency:"$",code:"AUD",flag:"🇰🇮"},
  {name:"Kuwait",currency:"KD",code:"KWD",flag:"🇰🇼"},
  {name:"Kyrgyzstan",currency:"с",code:"KGS",flag:"🇰🇬"},
  {name:"Laos",currency:"₭",code:"LAK",flag:"🇱🇦"},
  {name:"Latvia",currency:"€",code:"EUR",flag:"🇱🇻"},
  {name:"Lebanon",currency:"£",code:"LBP",flag:"🇱🇧"},
  {name:"Lesotho",currency:"L",code:"LSL",flag:"🇱🇸"},
  {name:"Liberia",currency:"$",code:"LRD",flag:"🇱🇷"},
  {name:"Libya",currency:"LD",code:"LYD",flag:"🇱🇾"},
  {name:"Liechtenstein",currency:"Fr",code:"CHF",flag:"🇱🇮"},
  {name:"Lithuania",currency:"€",code:"EUR",flag:"🇱🇹"},
  {name:"Luxembourg",currency:"€",code:"EUR",flag:"🇱🇺"},
  {name:"Madagascar",currency:"Ar",code:"MGA",flag:"🇲🇬"},
  {name:"Malawi",currency:"MK",code:"MWK",flag:"🇲🇼"},
  {name:"Malaysia",currency:"RM",code:"MYR",flag:"🇲🇾"},
  {name:"Maldives",currency:"ރ",code:"MVR",flag:"🇲🇻"},
  {name:"Mali",currency:"Fr",code:"XOF",flag:"🇲🇱"},
  {name:"Malta",currency:"€",code:"EUR",flag:"🇲🇹"},
  {name:"Marshall Islands",currency:"$",code:"USD",flag:"🇲🇭"},
  {name:"Mauritania",currency:"UM",code:"MRU",flag:"🇲🇷"},
  {name:"Mauritius",currency:"₨",code:"MUR",flag:"🇲🇺"},
  {name:"Mexico",currency:"$",code:"MXN",flag:"🇲🇽"},
  {name:"Micronesia",currency:"$",code:"USD",flag:"🇫🇲"},
  {name:"Moldova",currency:"L",code:"MDL",flag:"🇲🇩"},
  {name:"Monaco",currency:"€",code:"EUR",flag:"🇲🇨"},
  {name:"Mongolia",currency:"₮",code:"MNT",flag:"🇲🇳"},
  {name:"Montenegro",currency:"€",code:"EUR",flag:"🇲🇪"},
  {name:"Morocco",currency:"DH",code:"MAD",flag:"🇲🇦"},
  {name:"Mozambique",currency:"MT",code:"MZN",flag:"🇲🇿"},
  {name:"Myanmar",currency:"K",code:"MMK",flag:"🇲🇲"},
  {name:"Namibia",currency:"$",code:"NAD",flag:"🇳🇦"},
  {name:"Nauru",currency:"$",code:"AUD",flag:"🇳🇷"},
  {name:"Nepal",currency:"₨",code:"NPR",flag:"🇳🇵"},
  {name:"Netherlands",currency:"€",code:"EUR",flag:"🇳🇱"},
  {name:"New Zealand",currency:"$",code:"NZD",flag:"🇳🇿"},
  {name:"Nicaragua",currency:"C$",code:"NIO",flag:"🇳🇮"},
  {name:"Niger",currency:"Fr",code:"XOF",flag:"🇳🇪"},
  {name:"Nigeria",currency:"₦",code:"NGN",flag:"🇳🇬"},
  {name:"North Korea",currency:"₩",code:"KPW",flag:"🇰🇵"},
  {name:"North Macedonia",currency:"ден",code:"MKD",flag:"🇲🇰"},
  {name:"Norway",currency:"kr",code:"NOK",flag:"🇳🇴"},
  {name:"Oman",currency:"OMR",code:"OMR",flag:"🇴🇲"},
  {name:"Pakistan",currency:"₨",code:"PKR",flag:"🇵🇰"},
  {name:"Palau",currency:"$",code:"USD",flag:"🇵🇼"},
  {name:"Palestine",currency:"₪",code:"ILS",flag:"🇵🇸"},
  {name:"Panama",currency:"B/.",code:"PAB",flag:"🇵🇦"},
  {name:"Papua New Guinea",currency:"K",code:"PGK",flag:"🇵🇬"},
  {name:"Paraguay",currency:"₲",code:"PYG",flag:"🇵🇾"},
  {name:"Peru",currency:"S/.",code:"PEN",flag:"🇵🇪"},
  {name:"Philippines",currency:"₱",code:"PHP",flag:"🇵🇭"},
  {name:"Poland",currency:"zł",code:"PLN",flag:"🇵🇱"},
  {name:"Portugal",currency:"€",code:"EUR",flag:"🇵🇹"},
  {name:"Qatar",currency:"QR",code:"QAR",flag:"🇶🇦"},
  {name:"Romania",currency:"lei",code:"RON",flag:"🇷🇴"},
  {name:"Russia",currency:"₽",code:"RUB",flag:"🇷🇺"},
  {name:"Rwanda",currency:"Fr",code:"RWF",flag:"🇷🇼"},
  {name:"Saint Kitts and Nevis",currency:"$",code:"XCD",flag:"🇰🇳"},
  {name:"Saint Lucia",currency:"$",code:"XCD",flag:"🇱🇨"},
  {name:"Saint Vincent and the Grenadines",currency:"$",code:"XCD",flag:"🇻🇨"},
  {name:"Samoa",currency:"T",code:"WST",flag:"🇼🇸"},
  {name:"San Marino",currency:"€",code:"EUR",flag:"🇸🇲"},
  {name:"São Tomé and Príncipe",currency:"Db",code:"STN",flag:"🇸🇹"},
  {name:"Saudi Arabia",currency:"SR",code:"SAR",flag:"🇸🇦"},
  {name:"Senegal",currency:"Fr",code:"XOF",flag:"🇸🇳"},
  {name:"Serbia",currency:"din",code:"RSD",flag:"🇷🇸"},
  {name:"Seychelles",currency:"₨",code:"SCR",flag:"🇸🇨"},
  {name:"Sierra Leone",currency:"Le",code:"SLL",flag:"🇸🇱"},
  {name:"Singapore",currency:"S$",code:"SGD",flag:"🇸🇬"},
  {name:"Slovakia",currency:"€",code:"EUR",flag:"🇸🇰"},
  {name:"Slovenia",currency:"€",code:"EUR",flag:"🇸🇮"},
  {name:"Solomon Islands",currency:"$",code:"SBD",flag:"🇸🇧"},
  {name:"Somalia",currency:"Sh",code:"SOS",flag:"🇸🇴"},
  {name:"South Africa",currency:"R",code:"ZAR",flag:"🇿🇦"},
  {name:"South Korea",currency:"₩",code:"KRW",flag:"🇰🇷"},
  {name:"South Sudan",currency:"£",code:"SSP",flag:"🇸🇸"},
  {name:"Spain",currency:"€",code:"EUR",flag:"🇪🇸"},
  {name:"Sri Lanka",currency:"Rs",code:"LKR",flag:"🇱🇰"},
  {name:"Sudan",currency:"£",code:"SDG",flag:"🇸🇩"},
  {name:"Suriname",currency:"$",code:"SRD",flag:"🇸🇷"},
  {name:"Sweden",currency:"kr",code:"SEK",flag:"🇸🇪"},
  {name:"Switzerland",currency:"Fr",code:"CHF",flag:"🇨🇭"},
  {name:"Syria",currency:"£",code:"SYP",flag:"🇸🇾"},
  {name:"Taiwan",currency:"$",code:"TWD",flag:"🇹🇼"},
  {name:"Tajikistan",currency:"SM",code:"TJS",flag:"🇹🇯"},
  {name:"Tanzania",currency:"Sh",code:"TZS",flag:"🇹🇿"},
  {name:"Thailand",currency:"฿",code:"THB",flag:"🇹🇭"},
  {name:"Timor-Leste",currency:"$",code:"USD",flag:"🇹🇱"},
  {name:"Togo",currency:"Fr",code:"XOF",flag:"🇹🇬"},
  {name:"Tonga",currency:"T$",code:"TOP",flag:"🇹🇴"},
  {name:"Trinidad and Tobago",currency:"$",code:"TTD",flag:"🇹🇹"},
  {name:"Tunisia",currency:"DT",code:"TND",flag:"🇹🇳"},
  {name:"Turkey",currency:"₺",code:"TRY",flag:"🇹🇷"},
  {name:"Turkmenistan",currency:"T",code:"TMT",flag:"🇹🇲"},
  {name:"Tuvalu",currency:"$",code:"AUD",flag:"🇹🇻"},
  {name:"Uganda",currency:"Sh",code:"UGX",flag:"🇺🇬"},
  {name:"Ukraine",currency:"₴",code:"UAH",flag:"🇺🇦"},
  {name:"United Arab Emirates",currency:"AED",code:"AED",flag:"🇦🇪"},
  {name:"United Kingdom",currency:"£",code:"GBP",flag:"🇬🇧"},
  {name:"United States",currency:"$",code:"USD",flag:"🇺🇸"},
  {name:"Uruguay",currency:"$",code:"UYU",flag:"🇺🇾"},
  {name:"Uzbekistan",currency:"so'm",code:"UZS",flag:"🇺🇿"},
  {name:"Vanuatu",currency:"Vt",code:"VUV",flag:"🇻🇺"},
  {name:"Vatican City",currency:"€",code:"EUR",flag:"🇻🇦"},
  {name:"Venezuela",currency:"Bs",code:"VES",flag:"🇻🇪"},
  {name:"Vietnam",currency:"₫",code:"VND",flag:"🇻🇳"},
  {name:"Yemen",currency:"﷼",code:"YER",flag:"🇾🇪"},
  {name:"Zambia",currency:"ZK",code:"ZMW",flag:"🇿🇲"},
  {name:"Zimbabwe",currency:"$",code:"ZWL",flag:"🇿🇼"},
]

export type Country = typeof COUNTRIES[0]
