export const runtime = 'edge'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'
import Navbar from '@/components/Navbar'

export const metadata = {
  title: 'Terms of Service | BudgetPlan.AI',
  description: 'Terms of Service for BudgetPlan.AI - rules for using our AI financial planning service.',
}

export default async function TermsPage() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  return (
    <>
      <Navbar user={user} />
      <div style={{ maxWidth: 760, margin: '0 auto', padding: '48px 20px 80px' }}>
        <div style={{ marginBottom: 32 }}>
          <p style={{ fontSize: 13, color: 'var(--muted)', marginBottom: 8 }}>Last updated: June 3, 2026</p>
          <h1 style={{ fontFamily: 'var(--font-serif,serif)', fontSize: 36, letterSpacing: '-0.02em', marginBottom: 10 }}>Terms of Service</h1>
          <p style={{ color: 'var(--muted)', fontSize: 15, lineHeight: 1.7 }}>
            These Terms of Service govern your use of BudgetPlan.AI, a product of <a href="https://costsaverai.com" target="_blank" rel="noreferrer" style={{ color: 'var(--accent)', textDecoration: 'none' }}>CostSaver AI</a>. By using our service, you agree to these terms.
          </p>
        </div>

        {[
          {
            title: '1. Acceptance of Terms',
            content: `By creating an account or using BudgetPlan.AI, you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree, do not use the service.\n\nYou must be at least 16 years old to use BudgetPlan.AI.`
          },
          {
            title: '2. Not Financial Advice',
            content: `IMPORTANT: BudgetPlan.AI provides AI-generated financial information for educational and informational purposes only. Nothing on this platform constitutes:\n• Financial advice\n• Investment advice\n• Tax advice\n• Legal advice\n• Accounting advice\n\nAlways consult a qualified, licensed financial advisor before making any financial decisions. CostSaver AI and its products are not registered investment advisors.`
          },
          {
            title: '3. Your Account',
            content: `You are responsible for:\n• Maintaining the confidentiality of your login credentials\n• All activity that occurs under your account\n• Providing accurate information when creating your account\n• Notifying us immediately of any unauthorised use\n\nWe reserve the right to suspend or terminate accounts that violate these terms.`
          },
          {
            title: '4. Payments & Refunds',
            content: `BudgetPlan.AI offers a free tier and a one-time paid full report ($5).\n\nPayment: All payments are processed securely by Stripe. We do not store payment card information.\n\nRefund Policy: Due to the digital and immediate nature of our service (AI-generated plans are delivered instantly), all sales are final. If you experience a technical issue preventing delivery of your plan, contact us within 7 days at support@costsaverai.com for a full refund.`
          },
          {
            title: '5. Acceptable Use',
            content: `You agree not to:\n• Use the service for any unlawful purpose\n• Attempt to reverse-engineer, scrape, or extract data from our service\n• Share your account credentials with others\n• Use the service to harass, harm, or defraud others\n• Attempt to circumvent payment requirements\n• Use automated tools to generate plans at scale without permission\n\nViolation of these rules may result in immediate account termination without refund.`
          },
          {
            title: '6. Intellectual Property',
            content: `The BudgetPlan.AI platform, brand, and all associated content are owned by CostSaver AI.\n\nYour financial plans generated by the AI are yours to use for personal purposes. You may not resell, redistribute, or commercially exploit AI-generated plans without written permission.`
          },
          {
            title: '7. Accuracy of Information',
            content: `AI-generated financial plans are based on the information you provide. The quality of your plan depends on the accuracy of your inputs. We make no guarantee that:\n• Plans are accurate, complete, or up-to-date\n• Investment recommendations will perform as described\n• Business ideas will be profitable\n• Goal timelines are achievable\n\nPast performance of investment types mentioned is not indicative of future results.`
          },
          {
            title: '8. Limitation of Liability',
            content: `To the fullest extent permitted by law, CostSaver AI and BudgetPlan.AI shall not be liable for:\n• Any financial losses resulting from actions taken based on our plans\n• Indirect, incidental, or consequential damages\n• Loss of data or service interruptions\n• Third-party service failures (Stripe, Supabase, etc.)\n\nOur total liability to you for any claim shall not exceed the amount you paid us in the 12 months preceding the claim.`
          },
          {
            title: '9. Service Availability',
            content: `We aim to provide 99.9% uptime but do not guarantee uninterrupted service. We may:\n• Modify or discontinue features with notice\n• Perform scheduled maintenance\n• Experience unexpected outages\n\nWe are not liable for any losses caused by service unavailability.`
          },
          {
            title: '10. Governing Law',
            content: `These Terms are governed by and construed in accordance with applicable laws. Any disputes shall be resolved through binding arbitration rather than in court, except where prohibited by law.`
          },
          {
            title: '11. Changes to Terms',
            content: `We may update these Terms at any time. We will notify you of material changes via email or a notice on our website. Continued use of the service after changes constitutes acceptance.`
          },
          {
            title: '12. Contact',
            content: `Questions about these Terms?\n\nCostSaver AI\nEmail: legal@costsaverai.com\nWebsite: https://costsaverai.com`
          },
        ].map(s => (
          <div key={s.title} style={{ marginBottom: 32, paddingBottom: 32, borderBottom: '1px solid var(--border)' }}>
            <h2 style={{ fontSize: 18, fontWeight: 700, marginBottom: 12 }}>{s.title}</h2>
            <div style={{ fontSize: 14, color: 'var(--muted)', lineHeight: 1.8, whiteSpace: 'pre-line' }}>{s.content}</div>
          </div>
        ))}

        <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap', fontSize: 13 }}>
          <Link href="/privacy" style={{ color: 'var(--accent)', textDecoration: 'none' }}>Privacy Policy</Link>
          <Link href="/contact" style={{ color: 'var(--accent)', textDecoration: 'none' }}>Contact Us</Link>
          <a href="https://costsaverai.com" target="_blank" rel="noreferrer" style={{ color: 'var(--muted)', textDecoration: 'none' }}>CostSaver AI</a>
        </div>
      </div>
    </>
  )
}
